"""events.shift_id nullable

Revision ID: 7e2eb9c36560
Revises: 1f913968b2f7
Create Date: 2026-05-21 15:28:43.529952

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2eb9c36560'
down_revision: str | Sequence[str] | None = '1f913968b2f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'shift_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'shift_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
